"""
ENERGY OPTIMIZATION (UNCONSTRAINED + CONSTRAIN ENERGY DOMAIN)

We consider a one-hour generation scheduling problem with 14 power plants:

Units 1-5 : Coal-based thermal generators
Units 6-8 : Natural gas generators
Units 9-10: Hydroelectric generators
Units 11-12: Solar generators
Units 13-14: Wind generators

Variables (Python 0-based indexing):
  x[i]  for i=0 to 13
  x[i] is the power generated by unit i in MW during the hour.

Cost model (convex quadratic):
  cost(x)=sum_i(d[i]*x[i]^2+c[i]*x[i]

CONSTRAINED PROBLEM

Minimize cost(x) subject to:

1) Power balance (equality)
  h(x)=sum_i x[i]-D=0

2) Generator bounds (box constraints)
  0<=x[i]<=cap[i]  for all i

3) Emission cap (inequality)
  g_em(x)=sum(e[i]*x[i])-e_max<= 0

4) Renewable minimum (inequality)
  g_ren(x)=alpha*D-sum(renewables)<=0
  (equivalently: renewables>=alpha*D)

PROJECT STRUCTURE

Part A: Unconstrained problem (ONLY power balance enforced by eliminating x[13])
- solved by Newton's method.

Part B: Full constrained problem
- solved by Classical Lagrangian Relaxation.

For both parts we:
- Use two different starting points / multiplier sets.
- Record iteration counts and function evaluations.
- Plot convergence:
  Newton: log10(||grad F(y_k)||) vs iteration.
  LR: log10(constraint_violation_norm(x_k)) vs iteration.
"""

import numpy as np
import matplotlib.pyplot as plt

n=14   # number of generators
D=400.0  # total demand (MW)

#quadratic cost coefficients d[i] (Rs per MW^2)
d = np.array([
  0.0040,0.0045,0.0050,0.0042,0.0048,  # coal (1–5)
  0.0030,0.0032,0.0031,                 # gas  (6–8)
  0.0020,0.0022,                         # hydro (9–10)
  0.0010,0.0010,                        # solar (11–12)
  0.0010,0.0010                          # wind  (13–14)
])

#llinear cost coefficients c[i] (Rs per MW)
c = np.array([
  15.0,16.0,14.0,15.0,17.0,   #coal
  20.0,21.0,19.0,               #gas
  5.0,6.0,                      #hydro
  1.0,1.0,                      #solar
  2.0,2.0                       #wind
])

#capacity limits cap[i] (MW)
cap = np.array([
  80.0,80.0,75.0,70.0,70.0,   #coal
  60.0,60.0,50.0,               #gas
  40.0,40.0,                     #hydro
  30.0,30.0,                     #solar
  25.0,25.0                     #wind
])

#emission coefficients e[i] (tons CO2 per MW)
e = np.array([
  0.90,0.95,0.92,0.90,0.93,   #coal
  0.50,0.45,0.48,               #gas
  0.0,0.0,                      #hydro
  0.0,0.0,                      #solar
  0.0,0.0                      #wind
])

E_max=220.0 #emission cap (tons CO2)
alpha=0.25 #minimum renewable fraction (e.g. 25%)

#renewables are units 11-14 - indices from 10 to 13
renewable_indices = np.array([10, 11, 12, 13])


def total_cost(x: np.ndarray) -> float:
  #compute total generation cost.
  return float(np.sum(d * x**2 + c * x))



def demand_violation(x: np.ndarray) -> float:
  #power balance violation: sum x - D (should be 0).
  return float(np.sum(x) - D)


def emission_violation(x: np.ndarray) -> float:
  #emission violation: sum e[i]*x[i] - E_max (should be <= 0).
  return float(np.dot(e, x) - E_max)


def renewable_violation(x: np.ndarray) -> float:
    
  #renewable violation:alpha*D - sum(renewables) (should be <= 0).
  renew_sum = float(np.sum(x[renewable_indices]))
  return float(alpha * D - renew_sum)


def constraint_violation_norm(x: np.ndarray) -> float:
  """
  Combine equality and inequality violations into one number
  Used as convergence metric for constrained methods

  violation_norm=sqrt( h^2 + g_em^2 + g_ren^2 )
  """
  h=demand_violation(x)
  g_em=max(0.0, emission_violation(x))
  g_ren=max(0.0, renewable_violation(x))
  return float(np.sqrt(h**2 + g_em**2 + g_ren**2))


"""
UNCONSTRAINED PROBLEM (ONLY POWER BALANCE HANDLED)

We remove the equality sum x[i] = D by eliminating x[13]
x[13] = D - sum_{i=0..12} x[i]

Define y = [x[0],...,x[12]] in R^13
Define F(y) = total_cost(x(y))

We then solve:
minimize F(y)  over y in R^13   (no explicit bounds)

Because F is a strictly convex quadratic, the problem has a unique
global minimizer and Newton's method converges very fast.

NEWTON UPDATE FORMULA
At iteration k, we have point y_k:

  1) Compute gradient:
    g_k = grad_unconstrained(y_k)

  2) Solve linear system for Newton direction:
    H p_k = g_k
    where H is the Hessian matrix of F (constant).

  3) Step choice: full Newton step (alpha_k = 1):
    y_k+1 = y_k - p_k

STOPPING CRITERIA
We stop when either:

  - gradient norm is small:
    ||g_k|| < tol  (e.g. 1e-6)
  - or maximum iterations reached (max_iter).

Note: In this unconstrained part we do NOT enforce non-negativity orcapacity bounds, so the optimum may have negative components and
negative total cost. This is fine for the mathematical illustration.
"""


def build_full_x(y: np.ndarray) -> np.ndarray:
    """
    Build full 14-D vector x from 13-D vector y

    y holds x[0] to x[12]
    x[13] is chosen so that sum(x) = D
    """
    x = np.zeros(14)
    x[:13] = y
    x[13] = D - np.sum(y)
    return x


def f_unconstrained(y: np.ndarray, counter: dict | None = None) -> float:
    #reduced objective F(y) = total_cost(x(y))
    if counter is not None:
      counter["f"] += 1
    x = build_full_x(y)
    return total_cost(x)


def grad_unconstrained(y: np.ndarray) -> np.ndarray:
    """
    Gradient of F with respect to y.

    For i =0..12:
    dF/dy_i =2*d[i]*x[i]+c[i]-(2*d[13]*x[13] + c[13])

    This comes from chain rule and x[13] = D - sum(y).
    """
    x = build_full_x(y)
    x13 = x[13]
    g = np.zeros(13)
    for i in range(13):
      g[i] = 2 * d[i] * x[i] + c[i] - (2 * d[13] * x13 + c[13])
    return g


def hess_unconstrained() -> np.ndarray:
    """
    Hessian H of F(y). Since F is quadratic, H is constant.

    Diagonal entries:
      H[i,i] = 2*d[i] + 2*d[13]
    Off-diagonal entries (i != j):
      H[i,j] = 2*d[13]
    """
    H = np.zeros((13, 13))
    for i in range(13):
      for j in range(13):
        if i == j:
          H[i, j] = 2 * d[i] + 2 * d[13]
        else:
          H[i, j] = 2 * d[13]
    return H


H_const = hess_unconstrained()


def newton_method(y0: np.ndarray, tol: float = 1e-6, max_iter: int = 20):
    """
    Newton's method for the unconstrained reduced problem.

    Inputs:
      y0       - initial point in R^13
      tol      - gradient norm tolerance
      max_iter - maximum number of iterations

    Outputs:
      y        - final point
      history  - list of (iteration, F(y_k), ||grad F(y_k)||)
      evals    - number of function evaluations
    """
    y = y0.copy()
    H = H_const
    history = []
    eval_counter = {"f": 0}

    for k in range(max_iter):
      g=grad_unconstrained(y)
      f_val=f_unconstrained(y, eval_counter)
      norm_g=np.linalg.norm(g)

      history.append((k, f_val, norm_g))
      print(f"[Newton] Iter {k:2d} | "f"Cost = {f_val:12.4f} | "f"||grad|| = {norm_g:10.3e} | "f"sum(x) = {np.sum(build_full_x(y)):8.3f} | "f"min(x) = {np.min(build_full_x(y)):8.3f} | "f"max(x) = {np.max(build_full_x(y)):8.3f}")

      # stopping condition: small gradient
      if norm_g < tol:
        print("[Newton] Converged: gradient norm below tolerance.")
        break

      # newton direction: solve H p = g
      p=np.linalg.solve(H, g)

      # full step (alpha = 1)
      y=y-p

    evals=eval_counter["f"]
    return y,history,evals



"""
We now solve the constrained problem using classical Lagrangian Relaxation.

CONSTRAINTS USED:
  h(x)    = sum(x)-D =0
  g_em(x) = sum(e[i]*x[i])-E_max <=0
  g_ren(x)= alpha*D-sum(renewables) <=0
  bound box: 0<=x[i]<=cap[i]

LAGRANGIAN:
  L(x,lambda,mu,nu)=cost(x) + lambda*h(x)+ mu*g_em(x)+ nu*g_ren(x)

  lambda is free (can be any real number).
  mu,nu>= 0 (for inequality constraints).

ALGORITHM (at iteration k):

1) PRIMAL UPDATE (x^k+1):
  For fixed multipliers (lambda^k, mu^k, nu^k), we minimize L over x with only box constraints. This decomposes by generator.

  For each i, we minimize a 1D quadratic:
  d[i]*x[i]^2+(c[i]+lambda^k+mu^k*e[i]+gamma_i^k)*x[i]

  where gamma_i^k =-nu^k for renewable units (i in {10,11,12,13}),
  and gamma_i^k = 0 otherwise.

  Unconstrained minimizer:
    x_i_unbounded^k+1 = - (c[i] + lambda^k + mu^k*e[i] + gamma_i^k) / (2*d[i])

  Then enforce 0 <= x[i] <= cap[i] by clipping:
    x_i^k+1 = min( max(x_i_unbounded^k+1, 0), cap[i] )

2) DUAL UPDATE (lambda^k+1, mu^k+1, nu^k+1):

   Compute violations at x^k+1:
      h    = h(x^k+1)
      g_em = g_em(x^k+1)
      g_ren= g_ren(x^k+1)

   Update multipliers by gradient ascent on dual:

    lambda^k+1 = lambda^k + alpha_step * h
    mu^k+1= max( 0, mu^k + alpha_step * g_em )
    nu^k+1 = max( 0, nu^k + alpha_step * g_ren )

  Here alpha_step is a small positive step size.

We check:
  - total_cost(x_k)
  - constraint_violation_norm(x_k)

Because the objective is convex and constraints are linear,this scheme converges to the global optimum (primal feasible
and KKT-satisfying).
"""


def primal_minimizer_given_multipliers(lam: float,mu: float,nu: float) -> np.ndarray:
    #here at last the bound is placed on the x[i]
    x=np.zeros(14)
    for i in range(14):
      gamma_i= -nu if i in renewable_indices else 0.0
      b_i=c[i]+lam+mu*e[i]+gamma_i
      x_unbounded= -b_i/(2.0*d[i])
      x[i]=min(max(x_unbounded, 0.0),cap[i])
    return x


def lagrangian_relaxation(lam0: float,mu0: float,nu0: float,alpha_step: float = 1e-3,max_iter: int = 200):
   
    lam,mu,nu =lam0,mu0,nu0
    history=[]
    x=np.zeros(14)

    for k in range(max_iter):
        # primal update: xk+1
        x=primal_minimizer_given_multipliers(lam,mu,nu)

        # evaluate cost and constraint violations
        h=demand_violation(x)
        g_em=emission_violation(x)
        g_ren=renewable_violation(x)
        vnorm=constraint_violation_norm(x)
        cost_val=total_cost(x)

        history.append((k, cost_val, vnorm))

        print(f"[Lag] Iter {k:3d} | "f"Cost={cost_val:9.3f} | "f"h(x)={h:8.2e} | "f"g_em={g_em:8.2e} | "f"g_ren={g_ren:8.2e} | "f"||viol||={vnorm:8.2e} | "f"lambda={lam:7.3f}, myu={mu:7.3f}, v={nu:7.3f}")

        #  Dual updates: lambda^k+1, mu^k+1, nu^k+1
        lam=lam+alpha_step*h
        mu=max(0.0,mu+alpha_step*g_em)
        nu=max(0.0,nu+alpha_step*g_ren)

    return x,history,(lam,mu,nu)



def plot_newton_convergence(histories,labels,title):
    
    #plot log10(||grad||)vsiteration for Newton runs.histories: list of history lists from newton_method.
    
    plt.figure()
    for hist,label in zip(histories,labels):
      iters=[h[0] for h in hist]
      grad_norm=[h[2] for h in hist]
      grad_norm=np.maximum(grad_norm,1e-12)
      plt.plot(iters,np.log10(grad_norm),marker='o',label=label)
    plt.xlabel("Iteration number")
    plt.ylabel("log10(||gradient||)")
    plt.title(title)
    max_iter = max(len(h) for h in histories)
    plt.xticks(range(max_iter))
    plt.grid(True)
    plt.legend()
    plt.show()


def plot_constraint_convergence(histories,labels,title):
    
    #plot log10(constraint violation norm) vs iteration.histories: list of (k, cost, vnorm).
    
    plt.figure()
    for hist, label in zip(histories, labels):
      steps=[h[0] for h in hist]
      v=[h[2] for h in hist]
      v=np.maximum(v, 1e-12)
      plt.plot(steps, np.log10(v), marker='o', label=label)
    plt.xlabel("Iteration / step index")
    plt.ylabel("log10(constraint violation norm)")
    plt.title(title)
    plt.grid(True)
    plt.legend()
    plt.show()


if __name__ == "__main__":
    
    print("--------------- PART A: UNCONSTRAINED (NEWTON) -----------\n")

    # 2 starting points for y (13D)
    y0_equal=np.full(13, D / 14.0)  # equal sharing
    y0_biased=np.array([
        40, 40, 35, 30, 30,  # more on coal
        10, 10, 10,          # gas
        5, 5,                # hydro
        2, 2, 2              # some small values
    ], dtype=float)

    print("Running Newton from starting point 1 (equal share)...\n")
    y_star1, hist1, evals1 = newton_method(y0_equal)
    x_star1=build_full_x(y_star1)

    print("Running Newton from starting point 2 (biased)...\n")
    y_star2, hist2, evals2 = newton_method(y0_biased)
    x_star2=build_full_x(y_star2)
    print("Newton Results Summary")
    print(f"Start 1:iterations = {len(hist1)},function evals = {evals1}")
    print(f"Start 2:iterations = {len(hist2)},function evals = {evals2}")
    print(f"Start 1 cost={total_cost(x_star1):.4f}")
    print(f"Start 2 cost={total_cost(x_star2):.4f}")
    print(f"Sum x (start 1)={np.sum(x_star1):.4f} (should be {D})")
    print(f"Sum x (start 2)={np.sum(x_star2):.4f} (should be {D})")
    print(f"Difference between Newton solutions = "f"{np.linalg.norm(x_star1 - x_star2):.4e}")

    # plot newton convergence
    plot_newton_convergence([hist1, hist2],["Start 1 (equal)", "Start 2 (biased)"],"Unconstrained Newton: log10(||gradient||) vs iteration")

    
    print("\n\n----------- PART B: CONSTRAINED (LAGRANGIAN RELAXATION) -----------\n")

    # 2 different initial multiplier sets
    lam0_1,mu0_1,nu0_1=0.0,0.0,0.0
    lam0_2,mu0_2,nu0_2=1.0,0.5,0.5

    print("Running Lagrangian Relaxation from multipliers (0,0,0)")
    xL1,histL1,mult1=lagrangian_relaxation(lam0_1,mu0_1,nu0_1)

    print("\nRunning Lagrangian Relaxation from multipliers (1,0.5,0.5)")
    xL2,histL2,mult2=lagrangian_relaxation(lam0_2,mu0_2,nu0_2)

    print("\n Lagrangian Relaxation Results Summary ")
    print(f"Set 1: cost = {total_cost(xL1):.4f}")
    print(f" sum x={np.sum(xL1):.4f} (demand {D})")
    print(f" emissions={np.dot(e, xL1):.4f} (cap {E_max})")
    print(f" renewables={np.sum(xL1[renewable_indices]):.4f} "f"(min {alpha * D})")
    print(f" multipliers= {mult1}")

    print(f"\nSet 2: cost = {total_cost(xL2):.4f}")
    print(f" sum x={np.sum(xL2):.4f} (demand {D})")
    print(f" emissions={np.dot(e, xL2):.4f} (cap {E_max})")
    print(f" renewables={np.sum(xL2[renewable_indices]):.4f} "f"(min {alpha * D})")
    print(f" multipliers= {mult2}")

    print("\nLagrangian relaxation checks:")
    print("Constraint violation (set 1):",constraint_violation_norm(xL1))
    print("Constraint violation (set 2):",constraint_violation_norm(xL2))
    print("Difference between solutions:",np.linalg.norm(xL1 - xL2))

    # Plot LR convergence
    plot_constraint_convergence([histL1, histL2],["Lag multipliers set 1", "Lag multipliers set 2"],"Lagrangian Relaxation: log10(constraint violation) vs iteration")

    #for final reporting, pick any one of the two solutions as both are same
    x=xL1
    lam,mu,nu=mult1

    # print all generator outputs for constrained solution
    print("\n---- FINAL GENERATOR OUTPUTS (CONSTRAINED SOLUTION) ----\n")
    for i in range(14):
      print(f"x[{i+1:2d}] = {x[i]:8.4f} MW")

    print("---- FINAL CHECKS (CONSTRAINED) ----")
    print(f"Sum of generation = {np.sum(x):.4f} MW (Demand = {D})")
    print(f"Total cost        = {total_cost(x):.4f}")
    print(f"Total emissions   = {np.dot(e, x):.4f} (Cap = {E_max})")
    print(f"Renewable output  = {np.sum(x[renewable_indices]):.4f} "f"(Minimum = {alpha*D})")
    print(f"Final constraint violation norm = "f"{constraint_violation_norm(x):.3e}")
    print(f"Final multipliers (lambda,mu,nu)  ={lam:.4f}, {mu:.4f}, {nu:.4f}\n")

    print("Conclusion:")
    print("Newton: gradient norms small, same solution from two starts.")
    print("Lagrangian: constraint violation tiny, same solution from two multiplier sets.")